### ISSUE TITLE
Partless mode

### ISSUE THREAD

**Issue by RafiKueng** [RealGrep/protractor#1]
is there a possibility to add a partless mode, such that I could use this mod in combination with DarkMultiPlayer? (It bans non stock parts on rockets)

**Comment by RealGrep** [comment]
Not sure why I missed this for so long. My apologies. I will definitely look into that.

**Comment by RafiKueng** [comment]
no worries.. I'm using a hack to get this done I found in some forum:

put the following `protractor_on_all.cfg` in the `gamedata/protractor` folder:

```
//enables Protractor on all pods and probes

@PART[*]:HAS[@MODULE[ModuleCommand]]
{
    MODULE
    {name = ProtractorModule}
}
```

and delete / rename the `parts` folder. So far it worked great.

**Comment by RealGrep** [comment]
Newer versions (currently in pre-release but available from Github) no longer require the part to be there. It still exists, but is unnecessary. So, closing this.
